#!/bin/sh
ln -s req.cgi public
ln -s req.cgi page
ln -s req.cgi ssid
ln -s req.cgi network
ln -s req.cgi ssl
ln -s req.cgi firewall
ln -s req.cgi dhcp
ln -s req.cgi wwan
ln -s req.cgi syslog
ln -s req.cgi system
ln -s req.cgi logout
ln -s iot.cgi network_state
ln -s iot.cgi qos
ln -s iot.cgi apn
ln -s iot.cgi module
ln -s iot.cgi config
ln -s iot.cgi init
ln -s iot.cgi cnum
ln -s iot.cgi usim
ln -s iot.cgi getdata
