#!/bin/sh

cat $1 | sed 's/\\\\\//\//g' | sed 's/[{}]//g' | awk -v k="text" '{n=split($0,a,","); for (i=1; i<=n; i++) print a[i]}' | sed 's/\"\:\"/\ | /g' | sed 's/[\,]/ /g' | sed 's/\"//g' 
         
          
